### ISSUE TITLE
Reshow bars on each new slide?

### ISSUE THREAD

**Issue by splitbrain** [brutaldesign/swipebox#270]
I would be nice if the title bar would be shown on each new slide. I guess this could be achieved with a custom nextSlide() function and a call to showBars() but I can't get it to work. Any hints on how to achieve that?

**Comment by marvinhuebner** [comment]
Maybe i have a little hint for you. But in my solutions the bars are always displayed. I have edited the Scss file, so that the `transform: translate3d(0,-50px,0);` which is for displaying the bars is always available.

Before:

```scss
#swipebox-bottom-bar {
	bottom: -50px;

	&.visible-bars {
		transform: translate3d(0,-50px,0);
	}
}

#swipebox-top-bar {
	top: -50px;

	&.visible-bars {
		transform: translate3d(0,50px,0);
	}
}
```

After:

```scss
#swipebox-bottom-bar {
	bottom: -50px;

	&,
	&.visible-bars {
		transform: translate3d(0,-50px,0);
	}
}

#swipebox-top-bar {
	top: -50px;

	&,
	&.visible-bars {
		transform: translate3d(0,50px,0);
	}
}
```

Maybe that will help you.
